const express = require("express");
const router = express.Router();
const roleController = require("../controllers/roleController");
const authMiddleware = require("../middleware/authMiddleware");
const permissionMiddleware = require("../middleware/permissionMiddleware");
router.get("/", authMiddleware, permissionMiddleware("view_role"), roleController.getAll);
router.get("/:id", authMiddleware, permissionMiddleware("view_role"), roleController.getOne);
router.get("/:id/permissions", roleController.getPermissionsByRoleId);
//router.post("/", authMiddleware, permissionMiddleware("create_role"), roleController.create);
router.post("/", authMiddleware, roleController.create);
router.put("/:id", authMiddleware, permissionMiddleware("edit_role"), roleController.update);
router.patch("/:id", authMiddleware, permissionMiddleware("edit_role"), roleController.patch);
router.delete("/:id", authMiddleware, permissionMiddleware("delete_role"), roleController.delete);
router.put("/:id/permissions", authMiddleware,  roleController.assignPermissions);
module.exports = router;